name = "proof-in-bio"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-07-22"
assets = { directory = "./static/", binding = "ASSETS" }
routes = [
  { pattern = "proof-in-bio.com", custom_domain = true },
  { pattern = "www.proof-in-bio.com", custom_domain = true },
]
